export type RouteOrigin = "ported" | "new";
export type RouteRendering = "ssr" | "static" | "none";
export type RouteAuth = "public" | "session" | "admin";
export type RouteStatus = "todo" | "done" | "removed";

export interface RouteManifestEntry {
  path: string;
  origin: RouteOrigin;
  source: string;
  target: string | null;
  rendering: RouteRendering;
  auth: RouteAuth;
  services: string[];
  metadata: "generateMetadata" | "static" | "none";
  status: RouteStatus;
  fixture?: string;
  rationale?: string;
}

export const routeManifest: RouteManifestEntry[] = [
  {
    path: "/",
    origin: "ported",
    source: "FE/src/App.tsx:57",
    target: "app/(site)/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["articles.list", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/about",
    origin: "ported",
    source: "FE/src/App.tsx:58",
    target: "app/(site)/about/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/players",
    origin: "ported",
    source: "FE/src/App.tsx:59",
    target: "app/(site)/players/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["players.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/players/:id",
    origin: "ported",
    source: "FE/src/App.tsx:71",
    target: "app/(site)/players/[id]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["players.getById", "awards.listByPlayer", "stats.listByPlayer", "records.listByPlayer"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "playerId",
  },
  {
    path: "/teams",
    origin: "ported",
    source: "FE/src/App.tsx:60",
    target: "app/(site)/teams/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["teams.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/teams/:teamName",
    origin: "ported",
    source: "FE/src/App.tsx:61",
    target: "app/(site)/teams/[teamName]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["teams.getByName", "players.listByTeam", "games.listByTeam"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "teamName",
  },
  {
    path: "/games",
    origin: "ported",
    source: "FE/src/App.tsx:62",
    target: "app/(site)/games/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["games.listPlayed"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/games/:id",
    origin: "ported",
    source: "FE/src/App.tsx:63",
    target: "app/(site)/games/[id]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["games.getById", "stats.listByGame"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "gameId",
  },
  {
    path: "/seasons",
    origin: "ported",
    source: "FE/src/App.tsx:64",
    target: "app/(site)/seasons/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/seasons/:id",
    origin: "ported",
    source: "FE/src/App.tsx:65",
    target: "app/(site)/seasons/[id]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["seasons.getById", "teams.listBySeason", "games.listBySeason", "awards.listBySeason"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "seasonId",
  },
  {
    path: "/articles",
    origin: "ported",
    source: "FE/src/App.tsx:66",
    target: "app/(site)/articles/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["articles.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/articles/:id",
    origin: "ported",
    source: "FE/src/App.tsx:67",
    target: "app/(site)/articles/[id]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["articles.getById", "articles.likeStatus"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "articleId",
  },
  {
    path: "/articles/create",
    origin: "ported",
    source: "FE/src/App.tsx:74",
    target: "app/(site)/articles/create/page.tsx",
    rendering: "ssr",
    auth: "session",
    services: [],
    metadata: "static",
    status: "done",
    rationale:
      "old server used authenticateCombined on POST /api/articles, which accepts any authenticated user",
  },
  {
    path: "/awards",
    origin: "ported",
    source: "FE/src/App.tsx:73",
    target: "app/(site)/awards/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["awards.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/awards/:id",
    origin: "ported",
    source: "FE/src/App.tsx:72",
    target: "app/(site)/awards/[id]/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["awards.getById"],
    metadata: "generateMetadata",
    status: "done",
    fixture: "awardId",
  },
  {
    path: "/contact",
    origin: "ported",
    source: "FE/src/App.tsx:68",
    target: "app/(site)/contact/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/privacy-policy",
    origin: "ported",
    source: "FE/src/App.tsx:69",
    target: "app/(site)/privacy-policy/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/credits",
    origin: "ported",
    source: "FE/src/App.tsx:70",
    target: "app/(site)/credits/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/stats",
    origin: "ported",
    source: "FE/src/App.tsx:75",
    target: "app/(site)/stats/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["stats.leaderboard", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/vector-graph",
    origin: "ported",
    source: "FE/src/App.tsx",
    target: "app/(site)/vector-graph/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["stats.vectorGraph", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/schedules",
    origin: "ported",
    source: "FE/src/App.tsx:76",
    target: "app/(site)/schedules/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["games.listSchedule", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/applications",
    origin: "ported",
    source: "FE/src/App.tsx:77",
    target: "app/(site)/applications/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/faq",
    origin: "ported",
    source: "FE/src/App.tsx:78",
    target: "app/(site)/faq/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
  },
  {
    path: "/records",
    origin: "ported",
    source: "FE/src/App.tsx:79",
    target: "app/(site)/records/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["records.list", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/trivia",
    origin: "ported",
    source: "FE/src/App.tsx:80",
    target: "app/(site)/trivia/page.tsx",
    rendering: "ssr",
    auth: "public",
    services: ["trivia.randomPlayer", "trivia.randomTeam", "trivia.randomSeason"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/profile",
    origin: "ported",
    source: "FE/src/App.tsx:83",
    target: "app/(site)/profile/page.tsx",
    rendering: "ssr",
    auth: "session",
    services: ["users.profile", "articles.listByAuthor"],
    metadata: "static",
    status: "done",
    rationale: "unguarded in the SPA; the profile only ever renders the caller's own record",
  },
  {
    path: "/login",
    origin: "ported",
    source: "FE/src/App.tsx:84",
    target: "app/(site)/login/page.tsx",
    rendering: "static",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
    rationale:
      "reshaped: the username/password form is replaced by a single Roblox OAuth button",
  },
  {
    path: "/signup",
    origin: "ported",
    source: "FE/src/App.tsx:85",
    target: null,
    rendering: "none",
    auth: "public",
    services: [],
    metadata: "none",
    status: "removed",
    rationale:
      "Roblox OAuth is the only sign-in path, so there is no account to create locally",
  },
  {
    path: "/portal",
    origin: "ported",
    source: "FE/src/App.tsx:88",
    target: "app/portal/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: [
      "seasons.count",
      "teams.count",
      "players.count",
      "games.count",
      "stats.count",
      "records.count",
      "awards.count",
      "articles.count",
      "users.count",
    ],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/users",
    origin: "ported",
    source: "FE/src/App.tsx:99",
    target: "app/portal/users/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["users.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/players",
    origin: "ported",
    source: "FE/src/App.tsx:100",
    target: "app/portal/players/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["players.list", "teams.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/teams",
    origin: "ported",
    source: "FE/src/App.tsx:101",
    target: "app/portal/teams/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["teams.list", "seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/seasons",
    origin: "ported",
    source: "FE/src/App.tsx:102",
    target: "app/portal/seasons/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["seasons.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/games",
    origin: "ported",
    source: "FE/src/App.tsx:103",
    target: "app/portal/games/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["games.list", "seasons.list", "teams.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/stats",
    origin: "ported",
    source: "FE/src/App.tsx:104",
    target: "app/portal/stats/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["stats.list", "players.list", "games.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/records",
    origin: "new",
    source: "docs/REBUILD_PLAN.md#7",
    target: "app/portal/records/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: [
      "records.list",
      "records.latestJob",
      "seasons.list",
      "players.list",
      "games.list",
    ],
    metadata: "static",
    status: "done",
    rationale: "Admin surface for recalculating and editing record rows after the dashboard job panel was removed",
  },
  {
    path: "/portal/awards",
    origin: "ported",
    source: "FE/src/App.tsx:105",
    target: "app/portal/awards/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["awards.list", "seasons.list", "players.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/articles",
    origin: "ported",
    source: "FE/src/App.tsx:106",
    target: "app/portal/articles/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: ["articles.list"],
    metadata: "static",
    status: "done",
  },
  {
    path: "/portal/matches",
    origin: "ported",
    source: "FE/src/App.tsx:107",
    target: "app/portal/matches/page.tsx",
    rendering: "ssr",
    auth: "admin",
    services: [],
    metadata: "static",
    status: "removed",
  },
  {
    path: "/404",
    origin: "new",
    source: "docs/REBUILD_PLAN.md#7",
    target: "app/not-found.tsx",
    rendering: "ssr",
    auth: "public",
    services: [],
    metadata: "static",
    status: "done",
    rationale:
      "the SPA had no catch-all, so Netlify served index.html with HTTP 200 for unknown URLs",
  },
];

export const routeManifestByPath = new Map(routeManifest.map((entry) => [entry.path, entry]));
