/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 50edb3d93a0a4b7bc2b75409ac51a47d)
interface __BaseEnv_Env {
	UPLOADS: R2Bucket;
	DB: D1Database;
	RECORDS_QUEUE: Queue;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	ROBLOX_CLIENT_ID: string;
	ROBLOX_CLIENT_SECRET: string;
	ROOT_ROBLOX_IDS: string;
	IMAGES_RPC: Service /* entrypoint ImagesWorker from volley-images */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "ROBLOX_CLIENT_ID" | "ROBLOX_CLIENT_SECRET" | "ROOT_ROBLOX_IDS">> {}
}
