version: '3.8'

services:
  backend:
    build:
      context: .               # Keep the context as the BE directory
      dockerfile: Dockerfile     # Point to the Dockerfile outside the BE directory (root directory)
    volumes:
      - ./dist:/app/dist       # Only mount the dist directory
    ports:
      - "3000:3000"                 # Explicitly set port to 3000
    environment:
      - NODE_ENV=production
      - PORT=3000                   # Hardcode PORT for reliability
      - COOLIFY_URL=${COOLIFY_URL}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/volleyball
    depends_on:
      - db                          # Ensure DB service starts before backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=volleyball
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  postgres_data:
