services:
  backend:
    build:
      context: .               # Keep the context as the BE directory
      dockerfile: ./Dockerfile     # Point to the Dockerfile outside the BE directory (root directory)
    volumes:
      - ./dist:/app/dist       # Only mount the dist directory
    ports:
      - "3000:3000"                 # Explicitly set port to 3000
    environment:
      - NODE_ENV=production
      - PORT=3000                   # Hardcode PORT for reliability
      - DB_HOST=${DB_HOST}           # Database connection details for backend
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${URL}
    depends_on:
      - db                          # Ensure DB service starts before backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}     # Match variable names for PostgreSQL
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  postgres_data:
